version: '3.1'
services:
    postgres:
        image: 'postgres:15-alpine'
        working_dir: /var/www/html
        volumes:
            - 'db_postgres:/var/lib/postgresql/data'
        env_file:
            - .env
        ports:
            - '${POSTGRES_PORT}:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '${WEB_PORT}:80'
        env_file:
            - .env

    php-fpm:
        build: docker/php-fpm
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
        env_file:
            - .env

    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '1025:1025'
            - '8025:8025'
        env_file:
            - .env

    pgadmin:
        image: 'dpage/pgadmin4'
        ports:
            - '${PGADMIN_PORT}:80'
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

volumes:
    db_postgres:
